{"uuid": "cf46ac3b-0b9e-4309-9f0e-43d47492dd78", "children": ["da739436-b4a7-42c7-8ab9-75f04fac2441", "e92330b6-5f20-4a3c-b9d9-aa432d8b28c3", "9e086969-2578-43b4-a989-1602884f34fa", "81ea0e17-5801-4067-b815-419200bbe52f", "751557fd-9876-40af-8001-015b58968eee", "7a311887-6dd3-4cb2-a0f8-7f45dac5e1ea", "1dd6b7b2-2674-40fd-9ec3-b1f01fd1944f", "7d7aaa32-c4fd-495d-89a6-bc16e31eade7"], "befores": [{"name": "test_before", "status": "passed", "start": 1652930441735, "stop": 1652930464274}], "afters": [{"name": "test_before::0", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"test_before\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"F:\\git_reposittory\\myron_python\\autoUI\\xiaomi_search_test.py\", line 20, in test_before\n    self.test_before()\n  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1172, in result\n    fail(message, pytrace=False)\n  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\_pytest\\outcomes.py\", line 153, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "start": 1652930464563, "stop": 1652930464575}], "start": 1652930441735, "stop": 1652930464575}