{"uuid": "0d5b2157-24a5-4a84-8f9b-0539ab64632c", "children": ["52cfb3d3-0593-4556-9600-25c9a6805a1a", "bf9f71ab-83ac-4e8f-b11a-e23a9bebd566", "4114f8ba-1548-40fd-8117-736859329c8b", "62c6f2e2-a33a-4c89-9145-6458a63ce4f2", "7d05c12d-9b2c-4723-97f9-487852dc3bcd", "3db40e24-364b-4dbd-8ef5-ac199b594b64", "6aed7315-a2fb-4ce7-a6b4-f59fdfa4bfc8", "48b518aa-0d52-450d-8043-29f326ef5123"], "befores": [{"name": "test_before", "status": "passed", "start": 1653270944121, "stop": 1653270955059}], "afters": [{"name": "test_before::0", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"test_before\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"F:\\git_reposittory\\myron_python\\autoUI\\xiaomi_search_test.py\", line 21, in test_before\n    self.test_before()\n  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1172, in result\n    fail(message, pytrace=False)\n  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\_pytest\\outcomes.py\", line 153, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "start": 1653270955651, "stop": 1653270955713}], "start": 1653270944121, "stop": 1653270955713}