{"uuid": "d9f63c5a-f646-465d-a580-1eadff4da8c5", "children": ["667e09cf-ea71-44b1-88b6-8b8910680b0c", "b1c605ea-51ee-4440-bafa-f1bdbc72732d", "acc38b7a-b9e6-4a31-a49c-fb2a70802523", "687011e1-ca6d-4d0d-a611-36573fcf9207", "2ccd27a5-30df-44ae-b4bb-3f282507150d", "5f9f7029-69b3-4247-a082-3fbf6ef00e5a", "8689acc6-c82d-4ea3-9c80-eaec03fe4842", "951c5020-131e-4849-b9cc-7b58278d8b6f"], "befores": [{"name": "test_before", "status": "passed", "start": 1652930532881, "stop": 1652930539556}], "afters": [{"name": "test_before::0", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"test_before\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"F:\\git_reposittory\\myron_python\\autoUI\\xiaomi_search_test.py\", line 20, in test_before\n    self.test_before()\n  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1172, in result\n    fail(message, pytrace=False)\n  File \"E:\\development_tools\\python_tools\\Python38\\lib\\site-packages\\_pytest\\outcomes.py\", line 153, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "start": 1652930539877, "stop": 1652930539878}], "start": 1652930532881, "stop": 1652930539878}